name: search

services:
  backend:
    container_name: wretch
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/main/resources/config.properties:/app/config.properties
      - ./backend/data:/app/data
    depends_on:
      db:
        condition: service_started
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
      redis4:
        condition: service_healthy

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tramp
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      backend:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: .5g

  db:
    container_name: mongrel
    image: mongo:8.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    deploy:
      resources:
        limits:
          memory: 1.5G

  redis1:
    container_name: r1
    image: redis:8.8-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      start_interval: 1s
    ports:
      - "6379:6379"
    volumes:
      - redis_data1:/data
    deploy:
      resources:
        limits:
          memory: 1G

  redis2:
    container_name: r2
    image: redis:8.8-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      start_interval: 1s
    ports:
      - "6380:6379"
    volumes:
      - redis_data2:/data
    deploy:
      resources:
        limits:
          memory: 1G

  redis3:
    container_name: r3
    image: redis:8.8-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      start_interval: 1s
    ports:
      - "6381:6379"
    volumes:
      - redis_data3:/data
    deploy:
      resources:
        limits:
          memory: 1G

  redis4:
    container_name: r4
    image: redis:8.8-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
      start_interval: 1s
    ports:
      - "6382:6379"
    volumes:
      - redis_data4:/data
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  mongo_data:
  mongo_config:
  redis_data1:
  redis_data2:
  redis_data3:
  redis_data4: