name: search

services:
  backend:
    container_name: bastard
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/main/resources/config.properties:/app/config.properties
      - ./backend/data:/app/data
      - rocksdb_data:/app/index
    depends_on:
      db:
        condition: service_started
  #        cache:
  #          condition: service_healthy

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: tramp
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      backend:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 256M

  db:
    container_name: mongrel
    image: mongo:8.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    deploy:
      resources:
        limits:
          memory: 1G

#  cache:
#    container_name: cunt
#    image: redis:8.8-alpine
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      timeout: 3s
#      retries: 5
#      start_period: 5s
#      start_interval: 1s
#    ports:
#      - "6379:6379"
#    deploy:
#      resources:
#        limits:
#          memory: 2G

volumes:
  mongo_data:
  mongo_config:
  rocksdb_data: