FROM maven:3.9-eclipse-temurin-21-alpine AS build
WORKDIR /app

COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 mvn -B -ntp dependency:go-offline

COPY src ./src
RUN --mount=type=cache,target=/root/.m2 mvn -B -ntp package -DskipTests

FROM alpine:3.20 AS profiler-downloader

RUN wget https://github.com/async-profiler/async-profiler/releases/download/v4.4/async-profiler-4.4-linux-x64.tar.gz \
    && tar -xzf async-profiler-4.4-linux-x64.tar.gz

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup && mkdir data && chown appuser:appgroup data

COPY --from=profiler-downloader --chown=appuser:appgroup /async-profiler-4.4-linux-x64 /app/async-profiler
COPY --from=build --chown=appuser:appgroup /app/target/Distributed-Search-Engine-1.2-SNAPSHOT.jar app.jar

USER appuser
EXPOSE 8080
ENTRYPOINT ["java"]

CMD ["-XX:MaxRAMPercentage=70.0", "-XX:+UseZGC", "-jar", "app.jar"]

#CMD ["-XX:MaxRAMPercentage=70.0", \
#      "-XX:+UseZGC", \
#      "-agentpath:/app/async-profiler/lib/libasyncProfiler.so=start", \
#      "-jar", "app.jar"]

#CMD ["-XX:MaxRAMPercentage=70.0", \
#     "-XX:+UseZGC", \
#     "-XX:StartFlightRecording=duration=50s,filename=/tmp/recording.jfr,settings=profile", \
#     "-jar", "app.jar"]