FROM alpine:latest AS profiler
WORKDIR /downloads

RUN wget -qO- https://github.com/async-profiler/async-profiler/releases/download/v4.5/async-profiler-4.5-linux-x64.tar.gz | tar -xz

FROM maven:3.9.16-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
RUN --mount=type=cache,target=/root/.m2 mvn -B -ntp dependency:go-offline

COPY src ./src
RUN --mount=type=cache,target=/root/.m2 mvn -B -ntp package -DskipTests -o

FROM eclipse-temurin:21-jre
WORKDIR /app

RUN groupadd -r appgroup && useradd -r -g appgroup appuser && mkdir data index && chown appuser:appgroup data index

COPY --from=profiler --chown=appuser:appgroup /downloads/async-profiler-4.5-linux-x64 /app/async-profiler

COPY --from=build --chown=appuser:appgroup /app/target/libs/ /app/libs/
COPY --from=build --chown=appuser:appgroup /app/target/Sharded-Search-Engine-1.3.jar app.jar

USER appuser
EXPOSE 8080
ENTRYPOINT ["java"]

CMD ["-XX:MaxRAMPercentage=70.0", "-XX:+UseZGC", "-jar", "app.jar"]

#CMD ["-XX:MaxRAMPercentage=70.0", \
#      "-XX:+UseZGC", \
#      "-agentpath:/app/async-profiler/lib/libasyncProfiler.so=start", \
#      "-jar", "app.jar"]

#CMD ["-XX:MaxRAMPercentage=70.0", \
#     "-XX:+UseZGC", \
#     "-XX:StartFlightRecording=duration=45s,filename=/tmp/recording.jfr,settings=profile", \
#     "-jar", "app.jar"]